
# Créer 2 users

Booking.destroy_all
Friend.destroy_all
User.destroy_all

jean = User.new(
  pseudo: "JB",
  first_name: "Jean",
  last_name: "Bombeur",
  email: "BriocheDorée@beurre.com",
  password: "sandwichTriangle",
)

edgard = User.new(
  pseudo: "EA",
  first_name: "Edgard",
  last_name: "Avou",
  email: "milouf@army.com",
  password: "têtedechat",
)

jean.save!
edgard.save!

# Créer 10 friends
friends = [
  {
    name: "bob",
    date_of_birth: "19/04/1989",
    price: 301,
    genre: "man",
    address: "4 Av. Edgar Degas 56000 Vannes",
    activity_wedding: true,
    activity_sam: false,
    activity_diner: false,
    activity_birthday: false,
    activity_bowling: false,
    activity_hike: false,
    activity_movie: false,
    activity_picnic: true,
    activity_concert: true,
    activity_karaoke: true,
    activity_shopping: false,
    activity_sport: true,
    activity_barbecue: true,
    activity_camping: true,
    activity_paintball: true,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: false,
    default_cheap: false,
    default_arrogant: true,
    quality_funny: true,
    quality_reliable: false,
    quality_honest: false,
    quality_good_looking: false,
    quality_brave: false,
    picture: "https://randomuser.me/api/portraits/men/25.jpg"
  },
  {
    name: "marie",
    date_of_birth: "20/04/1989",
    price: 448,
    genre: "woman",
    address: "81 Av. de la Marne 56000 Vannes",
    activity_wedding: false,
    activity_sam: false,
    activity_diner: false,
    activity_birthday: false,
    activity_bowling: true,
    activity_hike: false,
    activity_movie: false,
    activity_picnic: true,
    activity_concert: false,
    activity_karaoke: true,
    activity_shopping: false,
    activity_sport: true,
    activity_barbecue: false,
    activity_camping: false,
    activity_paintball: true,
    default_complotist: true,
    default_impatient: false,
    default_disorganized: false,
    default_cheap: false,
    default_arrogant: false,
    quality_funny: true,
    quality_reliable: true,
    quality_honest: false,
    quality_good_looking: true,
    quality_brave: true,
    picture: "https://randomuser.me/api/portraits/women/67.jpg"
  },
  {
    name: "myriam",
    date_of_birth: "21/04/1989",
    price: 985,
    genre: "woman",
    address: "3 Imp. Philippe Lebon, 56000 Vannes",
    activity_wedding: true,
    activity_sam: true,
    activity_diner: true,
    activity_birthday: false,
    activity_bowling: true,
    activity_hike: false,
    activity_movie: true,
    activity_picnic: true,
    activity_concert: true,
    activity_karaoke: false,
    activity_shopping: true,
    activity_sport: true,
    activity_barbecue: false,
    activity_camping: false,
    activity_paintball: false,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: false,
    default_cheap: false,
    default_arrogant: true,
    quality_funny: false,
    quality_reliable: true,
    quality_honest: true,
    quality_good_looking: true,
    quality_brave: false,
    picture: "https://randomuser.me/api/portraits/women/31.jpg"
  },
  {
    name: "Ginette",
    date_of_birth: "22/04/1989",
    price: 273,
    genre: "woman",
    address: "12 Rue de la Brise, 56000 Vannes",
    activity_wedding: true,
    activity_sam: false,
    activity_diner: false,
    activity_birthday: true,
    activity_bowling: false,
    activity_hike: true,
    activity_movie: false,
    activity_picnic: false,
    activity_concert: false,
    activity_karaoke: false,
    activity_shopping: false,
    activity_sport: false,
    activity_barbecue: false,
    activity_camping: true,
    activity_paintball: true,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: false,
    default_cheap: true,
    default_arrogant: false,
    quality_funny: false,
    quality_reliable: false,
    quality_honest: false,
    quality_good_looking: true,
    quality_brave: false,
    picture: "https://randomuser.me/api/portraits/women/22.jpg"
  },
  {
    name: "Bernard",
    date_of_birth: "23/04/1989",
    price: 319,
    genre: "man",
    address: "19 Rue du Général Baron Fabre, 56000 Vannes",
    activity_wedding: false,
    activity_sam: false,
    activity_diner: false,
    activity_birthday: false,
    activity_bowling: true,
    activity_hike: false,
    activity_movie: false,
    activity_picnic: false,
    activity_concert: true,
    activity_karaoke: true,
    activity_shopping: false,
    activity_sport: true,
    activity_barbecue: false,
    activity_camping: true,
    activity_paintball: true,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: true,
    default_cheap: false,
    default_arrogant: true,
    quality_funny: false,
    quality_reliable: true,
    quality_honest: true,
    quality_good_looking: false,
    quality_brave: true,
    picture: "https://randomuser.me/api/portraits/men/72.jpg"
  },
  {
    name: "Luc",
    date_of_birth: "24/04/1989",
    price: 790,
    genre: "man",
    address: "35 Av. Clément Ader, 06100 Nice",
    activity_wedding: false,
    activity_sam: true,
    activity_diner: false,
    activity_birthday: true,
    activity_bowling: false,
    activity_hike: false,
    activity_movie: true,
    activity_picnic: true,
    activity_concert: true,
    activity_karaoke: true,
    activity_shopping: true,
    activity_sport: false,
    activity_barbecue: false,
    activity_camping: true,
    activity_paintball: false,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: false,
    default_cheap: true,
    default_arrogant: true,
    quality_funny: false,
    quality_reliable: true,
    quality_honest: true,
    quality_good_looking: false,
    quality_brave: false,
    picture: "https://randomuser.me/api/portraits/men/80.jpg"
  },
  {
    name: "Johnny Boy",
    date_of_birth: "25/04/1989",
    price: 151,
    genre: "man",
    address: "241 Av. de Pessicart, 06100 Nice",
    activity_wedding: false,
    activity_sam: false,
    activity_diner: true,
    activity_birthday: true,
    activity_bowling: true,
    activity_hike: false,
    activity_movie: true,
    activity_picnic: false,
    activity_concert: true,
    activity_karaoke: true,
    activity_shopping: false,
    activity_sport: false,
    activity_barbecue: true,
    activity_camping: false,
    activity_paintball: false,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: false,
    default_cheap: true,
    default_arrogant: false,
    quality_funny: true,
    quality_reliable: false,
    quality_honest: true,
    quality_good_looking: false,
    quality_brave: true,
    picture: "https://randomuser.me/api/portraits/men/90.jpg"
  },
  {
    name: "Lily",
    date_of_birth: "26/04/1989",
    price: 784,
    genre: "woman",
    address: "80 Av. de Brancolar, 06000 Nice",
    activity_wedding: false,
    activity_sam: false,
    activity_diner: true,
    activity_birthday: false,
    activity_bowling: false,
    activity_hike: true,
    activity_movie: false,
    activity_picnic: false,
    activity_concert: false,
    activity_karaoke: true,
    activity_shopping: false,
    activity_sport: false,
    activity_barbecue: true,
    activity_camping: true,
    activity_paintball: false,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: false,
    default_cheap: false,
    default_arrogant: false,
    quality_funny: false,
    quality_reliable: true,
    quality_honest: true,
    quality_good_looking: true,
    quality_brave: true,
    picture: "https://randomuser.me/api/portraits/women/23.jpg"
  },
  {
    name: "Marshall",
    date_of_birth: "27/04/1989",
    price: 854,
    genre: "man",
    address: "71 Av. Joseph Durandy, 06200 Nice",
    activity_wedding: false,
    activity_sam: false,
    activity_diner: false,
    activity_birthday: true,
    activity_bowling: false,
    activity_hike: false,
    activity_movie: false,
    activity_picnic: false,
    activity_concert: false,
    activity_karaoke: true,
    activity_shopping: true,
    activity_sport: true,
    activity_barbecue: false,
    activity_camping: true,
    activity_paintball: true,
    default_complotist: false,
    default_impatient: false,
    default_disorganized: true,
    default_cheap: false,
    default_arrogant: false,
    quality_funny: true,
    quality_reliable: false,
    quality_honest: false,
    quality_good_looking: false,
    quality_brave: false,
    picture: "https://randomuser.me/api/portraits/men/29.jpg"
  },
  {
    name: "Barney",
    date_of_birth: "28/04/1989",
    price: 238,
    genre: "man",
    address: "53-59 Prom. des Anglais, 06000 Nice",
    activity_wedding: true,
    activity_sam: true,
    activity_diner: false,
    activity_birthday: true,
    activity_bowling: false,
    activity_hike: true,
    activity_movie: true,
    activity_picnic: true,
    activity_concert: true,
    activity_karaoke: true,
    activity_shopping: true,
    activity_sport: false,
    activity_barbecue: true,
    activity_camping: true,
    activity_paintball: true,
    default_complotist: true,
    default_impatient: true,
    default_disorganized: true,
    default_cheap: true,
    default_arrogant: true,
    quality_funny: true,
    quality_reliable: false,
    quality_honest: false,
    quality_good_looking: false,
    quality_brave: true,
    picture: "https://randomuser.me/api/portraits/men/45.jpg"
  }
]

friends.each do |friend|
  seed = Friend.new(
    friend
  )
  seed.user = jean
  seed.save!
end

# Créer 1 bookings

booking = Booking.new(
  total_price: 100,
  status: "pending",
  start_date: "12/12/2023",
  end_date: "01/01/2024",
)

booking.user = edgard
bob = Friend.first
booking.friend = bob
booking.save!


